[package]
name = "nolauncher"
version = "0.0.0"
description = "A Tauri App"
authors = ["bloodnighttw"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = [ "window-all", "shell-open"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
open = "5.1.2"
oauth2 = "4.4.2"
tokio = { version = "1.25.0", features = ["full"] }
reqwest = { version = "0.12.4", features = ["json","blocking"] }
anyhow = "1.0.82"
thiserror = "1.0.59"
arboard = "3.4.0"

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

